version: "3.9"
services:
  bootstrap:
    image: alpine/curl:latest
    volumes:
      - ./start-osrm.sh:/start-osrm.sh
      - osrm-data:/data
    environment:
      MAP_URL: https://download.geofabrik.de/europe/iceland-latest.osm.pbf
    entrypoint: /start-osrm.sh download
  osrm-preprocess:
    depends_on:
      - bootstrap
    image: osrm/osrm-backend:latest
    volumes:
      - ./start-osrm.sh:/start-osrm.sh
      - osrm-data:/data
    command: /start-osrm.sh extract
  osrm:
    depends_on:
      - bootstrap
      - osrm-preprocess
    image: osrm/osrm-backend:latest
    ports:
      - 5005:5000
    volumes:
      - ./start-osrm.sh:/start-osrm.sh
      - osrm-data:/data
    command: /start-osrm.sh run
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8089:80
    environment:
      - NGINX_PORT=80
      - OSRM_URL="http://osrm:5005/"    
    depends_on:
      - osrm

volumes:
  osrm-data: